### ISSUE TITLE
generated code missing readBanana/writeBanana function declaration

### ISSUE THREAD

**Issue by audibleblink** [guervild/uru#4]
Generation command:
```
❯❯ uru generate -c config.yml -p thing.exe --exe --parameters "1.2.3.4 9090"
```

<details>
  <summary>Stack Trace</summary>

  ```
2:32PM FTL Error during build: error exit status 2: # huufoimw
./20220514_uwyS_main.go:17:5: imported and not used: "golang.org/x/sys/windows"
./20220514_uwyS_main.go:38:19: undefined: readBanana
./20220514_uwyS_main.go:45:8: undefined: writeBanana
./20220514_uwyS_main.go:52:18: undefined: readBanana
```

</details>

<details>
  <summary>Minimal Config to repro</summary>
  
```
payload:
  artifacts:
    - name: windows/bananaphone/local/go-shellcode-syscall
      type: injector
  type: dll
  arch: x64
  debug: false
```

</details>

**Comment by guervild** [comment]
Hello @audibleblink 

Yes, I forgot some stuff 😬 

I fix it in c2c32064ad6be037353ed50f0ebbc41d026d36d1 

It should work, do not hesitate if i can help ! 😄

**Comment by audibleblink** [comment]
oh nice. just missed your other comment.

with the same command and config I still get:

```
2:55PM FTL Error during build: error exit status 2: # ovrdcnds
./20220514_jqLZ_main.go:17:5: imported and not used: "golang.org/x/sys/windows"
```

**Comment by audibleblink** [comment]
err. sorry, not same config. This config

```yml
payload:
  artifacts:
    - name: windows/bananaphone/local/go-shellcode-syscall
      type: injector
    - name: patchetw
      type: evasion
      args:
        - name: UseBanana
          value: true
  type: dll
  arch: x64
  debug: false
```


```
2:55PM FTL Error during build: error exit status 2: # ovrdcnds
./20220514_jqLZ_main.go:17:5: imported and not used: "golang.org/x/sys/windows"
```



edit:

If i delete:

```yml
      args:
        - name: UseBanana
          value: true
```

it runs perfectly.
